# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=1)),
                ('splashImg', models.CharField(max_length=40)),
                ('link', models.URLField(max_length=50)),
                ('skills', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
