# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuiltApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='orderID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
